name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: |
          echo 'Github cannot connect to php.net due to the bug referred here: https://bugs.php.net/bug.php?id=79445'
          echo 'By-pass the build-docker phase for now'
          echo 'make build-docker'
