name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: make build-docker
